// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// logLL_rcpp
double logLL_rcpp(NumericVector par, List locus_info, NumericVector log_freq);
RcppExport SEXP _gemrich_logLL_rcpp(SEXP parSEXP, SEXP locus_infoSEXP, SEXP log_freqSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type par(parSEXP);
    Rcpp::traits::input_parameter< List >::type locus_info(locus_infoSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type log_freq(log_freqSEXP);
    rcpp_result_gen = Rcpp::wrap(logLL_rcpp(par, locus_info, log_freq));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_gemrich_logLL_rcpp", (DL_FUNC) &_gemrich_logLL_rcpp, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_gemrich(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
